#!/usr/bin/env bash
# One-time container setup: load .env, warm the dependency cache, generate the
# development mTLS certificates, and install the OMP agent.
set -euo pipefail

WORKSPACE="${1:-/workspaces/ibkr.rs}"
cd "$WORKSPACE"

echo "=== ibkr.rs post-create ==="

ENV_FILE="$WORKSPACE/.env"

# Parse .env line by line instead of sourcing it: values may contain spaces or
# quotes, which `source` would try to execute.
parse_env() {
    grep -v '^\s*#' "$ENV_FILE" | grep -v '^\s*$'
}

strip_value() {
    local value="$1"
    value="${value%%[[:space:]]#*}" # trailing inline comment
    value="${value%\"}"; value="${value#\"}"
    value="${value%\'}"; value="${value#\'}"
    printf '%s' "$value"
}

if [ -f "$ENV_FILE" ]; then
    echo "loading $ENV_FILE"

    # Export for this script and its children (cargo fetch, gen-dev-certs).
    set -a
    while IFS='=' read -r key value; do
        [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
        export "$key=$(strip_value "$value")"
    done < <(parse_env)
    set +a

    # Persist for interactive shells (single-quoted, so spaces are safe).
    PROFILE=/etc/profile.d/ibkr-env.sh
    {
        echo "# Auto-generated by .devcontainer/post-create.sh from $ENV_FILE"
        echo "# Do not edit; change $ENV_FILE and re-run post-create instead."
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
            printf "export %s='%s'\n" "$key" "$(strip_value "$value")"
        done < <(parse_env)
    } | sudo tee "$PROFILE" >/dev/null
    echo "environment persisted to $PROFILE"
else
    echo "no .env found; compose-provided defaults apply (.env.example documents them)"
fi

echo ".> fetching dependencies"
cargo fetch

echo ".> generating development certificates"
"$WORKSPACE/scripts/gen-dev-certs.sh"

# OMP coding agent, so the container has an agent available. The installer
# fetches the latest release binary into ~/.local/bin (non-interactive); the
# image puts that directory on PATH.
#
# Checked by path rather than `command -v`: this script may run before PATH has
# been refreshed, which would otherwise re-download on every invocation.
OMP_BIN="${PI_INSTALL_DIR:-$HOME/.local/bin}/omp"
if [ -x "$OMP_BIN" ]; then
    echo ".> omp already installed at $OMP_BIN"
else
    echo ".> installing omp"
    curl -fsSL https://omp.sh/install | sh
fi
echo "omp: $("$OMP_BIN" --version 2>/dev/null || echo 'not runnable')"

echo "=== post-create complete ==="
echo "  cargo build          # compile"
echo "  cargo run -- health  # probe the gateway"
echo "  just gateway-up      # start the gateway (opt-in compose profile)"
echo "  omp                  # coding agent in this container"
