#!/usr/bin/env bash
# One-time container setup: load .env, warm the dependency cache, and generate
# the development mTLS certificates.
set -euo pipefail

WORKSPACE="${1:-/workspaces/ibkr.rs}"
cd "$WORKSPACE"

echo "=== ibkr.rs post-create ==="

ENV_FILE="$WORKSPACE/.env"

# Parse .env line by line instead of sourcing it: values may contain spaces or
# quotes, which `source` would try to execute.
parse_env() {
    grep -v '^\s*#' "$ENV_FILE" | grep -v '^\s*$'
}

strip_value() {
    local value="$1"
    value="${value%%[[:space:]]#*}" # trailing inline comment
    value="${value%\"}"; value="${value#\"}"
    value="${value%\'}"; value="${value#\'}"
    printf '%s' "$value"
}

if [ -f "$ENV_FILE" ]; then
    echo "loading $ENV_FILE"

    # Export for this script and its children (cargo fetch, gen-dev-certs).
    set -a
    while IFS='=' read -r key value; do
        [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
        export "$key=$(strip_value "$value")"
    done < <(parse_env)
    set +a

    # Persist for interactive shells (single-quoted, so spaces are safe).
    PROFILE=/etc/profile.d/ibkr-env.sh
    {
        echo "# Auto-generated by .devcontainer/post-create.sh from $ENV_FILE"
        echo "# Do not edit; change $ENV_FILE and re-run post-create instead."
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
            printf "export %s='%s'\n" "$key" "$(strip_value "$value")"
        done < <(parse_env)
    } | sudo tee "$PROFILE" >/dev/null
    echo "environment persisted to $PROFILE"
else
    echo "no .env found; compose-provided defaults apply (.env.example documents them)"
fi

echo ".> fetching dependencies"
cargo fetch

echo ".> generating development certificates"
"$WORKSPACE/scripts/gen-dev-certs.sh"

echo "=== post-create complete ==="
echo "  cargo build          # compile"
echo "  cargo run -- health  # probe the gateway"
echo "  just gateway-up      # start the gateway (opt-in compose profile)"
